### ISSUE TITLE
self signed ssl issue

### ISSUE THREAD

**Issue by odra** [ktdreyer/koji-ansible#229]
Hello,

I am using the following config file for a profile:

```
[sample]
weburl = https://koji-hub:8443/koji
topurl =  https://koji-hub:8443
server =  https://koji-hub:8443/kojihub

;auth
cert = /etc/certs/client.pem
serverca = /etc/certs/ca.pem
authtype = ssl
no_ssl_verify = True
```

But I am getting the following error:
```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain
```

Is this a bug or am I missing something in the config file?

**Comment by ktdreyer** [comment]
A couple of things to check:

- Where is your Koji configuration file located? If it's located in `$HOME/.koji/config.d/sample.conf`, Ansible might be using `sudo` and it cannot read the configuration because `$HOME` will be different. Is there any other configuration for the `[sample]` profile anywhere else, like in `/etc/koji.conf` or `/etc/koji.conf.d/`? It's strange that your `no_ssl_verify` setting is not respected here.

- When you use the CLI independently of Ansible, do you get the same `certificate verify failed: self signed certificate in certificate chain` error?
  - `koji -p sample list-hosts` - this will not authenticate, it will just make an HTTPS request to `https://koji-hub:8443/kojihub` , asking for the list of builder hosts configured on the hub.
  - `koji -p sample hello` - this will authenticate you to the hub (performing SSL client auth request to `https://koji-hub:8443/kojihub/ssllogin`)

- Are you able to successfully make an HTTP request to the hub with `curl`, independent of the koji client?

  A request that performs no authentication:
  ```
  curl \
    --cacert /etc/certs/ca.pem \
    https://koji-hub:8443/kojihub
  ```
  With authentication (note you'll need to split out your user's public cert and private key into separate files here...):
  ```
  curl \
    --cacert /etc/certs/ca.pem \
    --cert /etc/certs/cert.pem \
    --key /etc/certs/cert.key \
    https://koji-hub:8443/kojihub/ssllogin
  ```

Both of those `curl` commands should show `Method Not Allowed This is an XML-RPC server. Only POST requests are accepted.`, but that's fine, we just want to make sure there are no TLS errors.

**Comment by odra** [comment]
I am using  the `koji_user` module within a container and my profile file is located at `$HOME/.koji/config.d/sample.conf`:

```
- ktdreyer.koji_ansible.koji_user:
        koji: sample
        name: someuser
        permissions: [admin]
```

**Comment by odra** [comment]
Using curl does not give me a ssl error:

```
curl -k -X POST \
  --cacert /opt/ansible/.koji/certs/sample/ca.pem \
  --cert /opt/ansible/.koji/certs/sample/cert.pem \
  --key /opt/ansible/.koji/certs/sample/key.pem \
  https://koji-hub:8443/kojihub/ssllogin
```

**Comment by odra** [comment]
Also, the koji CLI does not give an error.

I have my own implementation where I call "ssl_login" specifying both cert and ca files: https://pagure.io/kube-sig/koji-operator/blob/main/f/operator/roles/koji-lib/library/koji_user.py#_140 - I am wondering if this is causing the issue.

**Comment by ktdreyer** [comment]
Thank you for the details. 

A few things stand out to me with that curl command:
1. You ran `curl` with `/opt/ansible/.koji/certs/sample/ca.pem` and the koji profile mentions `/etc/certs/ca.pem` - do those files have the same contents?
2. The `-k` command to `curl` will skip CA validation, so it won't print any errors if the hub CA did not match `--cacert`.

Is there any way to increase Ansible's verbosity (like with `-vvv`) ? That will tell us a lot about how Ansible is executing.

That's an interesting `koji_user` module, thanks for mentioning that code.

Maybe there is some additional information we could be logging in Koji or Ansible, like "what profile were we using" and "what were all the client settings" when we hit a SSL error.

**Comment by odra** [comment]
1. yes they are the same file, I just used dummy values for the sake of the example ;)
2. 2. Yes, the CA is self-signed so it can't be validated as a valid authority and I can't use commands such as `update-ca-trust` because I am running those commands/ansible modules inside a container (which why I am using the `no_ssl_verify` property).

Here is the log output using the `-vvv` flag: https://gist.github.com/odra/1e1ff20283c1e4540e3cf96d49f375b1

**Comment by odra** [comment]
I was taking a look this part of the koji codebase: https://pagure.io/koji/blob/master/f/koji/__init__.py#_2687 - so it will skip the CA verification if "serverca" is not set which makes sense I think?

I removed "serverca" from my configuration file and the module worked.

**Comment by ktdreyer** [comment]
Yeah, that sounds like a Koji bug to me. I would expect `no_ssl_verify = True` to always disable CA validation, like curl's `-k` option.

All simple CAs are self-signed. I wonder if there is something else going on with the CA you generated? Maybe it doesn't have the field?

You might try https://pagure.io/koji-tools/blob/master/f/src/bin/koji-ssl-admin .I designed this tool to make the SSL setup process easier. I want to move this code into a `koji` sub-command [eventually](https://lists.fedorahosted.org/archives/list/koji-devel@lists.fedorahosted.org/message/YJFISMJHWCCPKM5JEXTMGFYM25VS5KBR/).

Here's how I use `koji-ssl-admin` in Ansible: https://github.com/ktdreyer/koji-playbooks/blob/master/roles/koji-ssl-admin/tasks/main.yml

**Comment by odra** [comment]
Thanks for sharing, I will definitely take a look at my CA generation code.

Closing this issue since it is not a koji-ansible issue.

Thanks for the help!

**Comment by ktdreyer** [comment]
Sure. I want to look more into this `no_ssl_verify` issue, though.

**Comment by odra** [comment]
I may give koji-ssl-ansible a try but I wanted to share how I am generating a client pem file using the openssl library in an action plugin: https://pagure.io/kube-sig/koji-operator/blob/main/f/operator/roles/koji-lib/action_plugins/koji_client_cert.py (the action plugin made things a bit easier to remove complex logic from the task yaml code).

**Comment by ktdreyer** [comment]
This is very cool. Thanks for sharing. That's a neat way to build an action module too - I hadn't considered doing something like that.

I looked up the docs for [`openssl_csr_module`](https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_csr_module.html) module. Looks like you can set `extended_key_usage` to `clientAuth` for the client certificates.

**Comment by odra** [comment]
Oh looks like I am missing from my CA certificate but is interesting that both kojid and kojira do not show that error.

**Comment by ktdreyer** [comment]
Yes, I wonder if that's a mod_ssl thing or what.

For example, I think eventually CommonName is going to be completely deprecated. There have been hints that agents will no longer respect CommonName, eg. https://community.letsencrypt.org/t/how-to-obtain-a-cert-without-a-common-name/72807 , and eventually all software will only perform verifications according to subjectAltNames. This is the kind of thing that I want to make easier for Koji admins via koji-ssl-admin.

**Comment by odra** [comment]
That's interesting.. do you think it will make sense to also add some ssl validation in Koji itself eventually (for now all validation happens at the apache level right?)?

**Comment by ktdreyer** [comment]
Now that you mention it, if you follow the [server howto](https://docs.pagure.org/koji/server_howto/), mod_ssl will only validate that the certificate is signed by the CA in `SSLCACertificateFile`. Apache doesn't do any further authorization. (apparently [that would be the `SSLRequire` directive](https://serverfault.com/questions/746810/enforcing-client-verification-in-apache-just-for-a-specific-client-certificate), and the server howto docs don't recommend that.)

mod_ssl sends all the client SSL information to mod_wsgi, and mod_wsgi provides that to the Koji Hub and Web apps. Koji's hub has a `DNUsernameComponent` setting that allows administrators to configure how Koji should determine usernames from certificates. By default, this is `DNUsernameComponent = CN`. Looks like this could be any part of the DN.

Thinking about this further, maybe it makes more sense to default Koji to using a "UID" component instead of the "CN". I think most orgs will distribute SSL certificates to users with usernames in the "UID" component instead of CN (at least Red Hat Certificate Server does this.

I think I'll add support to `koji-ssl-admin` to write a UID component onto each user certificate. Currently koji-ssl-admin only writes the username as the CN.

**Comment by ktdreyer** [comment]
Also, I've added the "UID" attribute to client certs in https://pagure.io/koji-tools/pull-request/57
